FROM buddycompiler-base:v1.0

ENV DEBIAN_FRONTEND=noninteractive

# Install necessary packages
RUN apt-get update && apt-get install -y python3-dev \
    && rm -rf /var/lib/apt/lists/*

# Set up the environment
ENV USER=root
ENV HOME=/root
WORKDIR /root

# Set the working directory to /root
WORKDIR /root