FROM buddycompiler-base:v1.1

ENV DEBIAN_FRONTEND=noninteractive

# Set up the environment
ENV USER=root
ENV HOME=/root
WORKDIR /root

# Clone your repository

# Set the working directory to /root
WORKDIR /root

# Initialize submodules