FROM buddycompiler-base:v1.0

ENV DEBIAN_FRONTEND=noninteractive

# Install necessary packages
RUN apt-get update && apt-get install -y lld \
    && rm -rf /var/lib/apt/lists/*

# Set up the environment
ENV USER=root
ENV HOME=/root
WORKDIR /root

# Clone your repository
RUN git clone https://github.com/buddy-compiler/buddy-mlir.git
WORKDIR /root/buddy-mlir

# Initialize submodules
RUN git submodule update --init